# Generated by Django 5.1.4 on 2024-12-13 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library_blog', '0007_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=10)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_blog.bookmodel')),
                ('tags', models.ManyToManyField(to='age_limit.tag')),
            ],
        ),
    ]
