# Generated by Django 5.1.4 on 2024-12-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='book_images/', verbose_name='Загрузите фото книги')),
                ('title', models.CharField(max_length=100, verbose_name='Укажите название книги')),
                ('description', models.TextField(blank=True, verbose_name='Укажите описание книги')),
                ('price', models.FloatField(default=10, verbose_name='Укажите цену книги')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genre', models.CharField(choices=[('Фантастика', 'Фантастика'), ('Детектив', 'Детектив'), ('Приключения', 'Приключения')], default='Фантастика', max_length=100)),
                ('authors_mail', models.EmailField(blank=True, max_length=100, verbose_name='Укажите почту автора')),
                ('author', models.CharField(max_length=100, verbose_name='Укажите имя автора')),
            ],
        ),
    ]
