# Generated by Django 5.1.4 on 2024-12-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='trailer',
            field=models.URLField(null=True, verbose_name='Укажите ссылку на видео'),
        ),
    ]
