# Generated by Django 5.1.4 on 2024-12-12 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_blog', '0003_alter_bookmodel_options_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.CharField(choices=[('⭐', '⭐'), ('⭐⭐', '⭐⭐'), ('⭐⭐⭐', '⭐⭐⭐'), ('⭐⭐⭐⭐', '⭐⭐⭐⭐'), ('⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐')], default='⭐', max_length=100, null=True, verbose_name='Поставьте оценку'),
        ),
    ]
