# Generated by Django 5.1.4 on 2024-12-12 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_blog', '0004_alter_review_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='film',
        ),
        migrations.AddField(
            model_name='review',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='library_blog.bookmodel'),
        ),
    ]
