# Generated by Django 5.1.4 on 2024-12-17 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('age_limit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Укажите ваше имя')),
                ('email', models.EmailField(max_length=100, verbose_name='Укажите почту')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Укажите номер телефона')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='age_limit.book', verbose_name='Выберите книгу')),
            ],
        ),
    ]
